### ISSUE TITLE
Project settings: Add warning if static batching is enabled when Hybrid package is present

### ISSUE THREAD

**Issue by unitystevem** [mtrive/ProjectAuditor#105]
Long story short, having static-batched GameObjects in subscenes that will be converted and rendered with Hybrid is a Very Bad Idea. Hybrid batching is wildly different, and trying to combine it with static batching causes all kinds of problems (and no tangible performance benefit). The plan is to have Hybrid V2 disable the static mesh combining in the project settings when the package is included in the project - but presumably users would be able to re-enable it if they wanted to, and presumably we could have the Project Auditor warn about such things, even before the changes allowing Hybrid to disable the option

**Comment by mtrive** [comment]
Is there a way to know whether static batching is enabled via editor API ?

**Comment by unitystevem** [comment]
Ah, good point. There isn't, which is why there isn't already a database entry encouraging it to be enabled in the standard, non-DOTS case. This one might not be possible, then.

**Comment by mtrive** [comment]
I found PlayerSettings.GetBatchingForPlatform(), it's _internal_ though.

**Comment by unitystevem** [comment]
Does that mean we don't have access to it from inside a package? Or can we access it but without guarantees that the API won't change?

**Comment by mtrive** [comment]
I think both. Anyway, we can use Reflection:
`private static bool IsStaticBatchingEnabled(BuildTarget platform)
{
    var method = typeof(PlayerSettings).GetMethod("GetBatchingForPlatform", BindingFlags.Static | BindingFlags.Default | BindingFlags.NonPublic);
    if (method == null)
    {
        throw new NotSupportedException("Getting batching per platform is not supported");
    }

    var staticBatching = 0;
    var dynamicBatching = 0;
    var args = new object[]
    {
        platform,
        staticBatching,
        dynamicBatching    
    };

    method.Invoke(null, args); ;
    return (bool)args[1];
}`
