### ISSUE TITLE
Feature request: add import csv functionality

### ISSUE THREAD

**Issue by paulg-unity** [mtrive/ProjectAuditor#137]
It would be great if one could import a csv file that has been exported to have a GUI to investigate issues seen on a project.
Thanks! ✌️

**Comment by mtrive** [comment]
With next release you will be able to save **and load** the whole report in json format. For reference: https://github.com/Unity-Technologies/ProjectAuditor/pull/32

BTW, you can also still export to csv.

Please re-open an issue in the Unity repo if you still feel the need to be able to import csv.
