### ISSUE TITLE
Add option to only list issues in methods that are actually referenced by the project 

### ISSUE THREAD

**Issue by mtrive** [mtrive/ProjectAuditor#23]
Right now, the tool will go through all assemblies looking for issues. We should make it a bit smarter so that the user can see only issues in methods that are referenced by the project.

- We might be able to implement this by looking at all MonoBehaviour methods and traversing all callees.
- This should be optional

**Comment by unitystevem** [comment]
This is a great idea, if it's possible. Will cut down on the chatter from packages for most projects.

**Comment by mtrive** [comment]
I believe this can only be done by analysing the compiled assemblies after making a Build. The problem here is to find the assemblies in the project Temp folder making sure they are already stripped of unused code.
