### ISSUE TITLE
Package manager compliance

### ISSUE THREAD

**Issue by unitystevem** [mtrive/ProjectAuditor#27]
The project should be made Package Manager compliant, with a view to perhaps one day making it an official Unity package.

Porting the code to the framework laid out in the Package Starter Kit seems to be the best way to do this.

https://github.cds.internal.unity3d.com/unity/com.unity.package-starter-kit

**Comment by mtrive** [comment]
This can be done whilst adding the package to Yamato. Work has started in yamato branch.

**Comment by mtrive** [comment]
I think this is done. As any specific problem arises, we will enter a new issue.
