### ISSUE TITLE
[API] Run from command line

### ISSUE THREAD

**Issue by unitystevem** [mtrive/ProjectAuditor#64]
I have a customer who would like the ability to run the Project Auditor from the command line. The use-case would be to incorporate it in a Jenkins build, so there could be a build step which could launch Unity, run the Project Auditor analysis, and export the findings. This could be diffed (presumably via some external tool) against a cached result from a previous run in order to report on any new issues that have shown up in the project since the previous build.

**Comment by mtrive** [comment]
They should be able to run the editor via command line and execute a method like this:

`static class MyClass
{
   static void AnalyzeAndExport()
   {
      var projectAuditor = new ProjectAuditor();
      var projectReport = projectAuditor.Audit();
      projectReport.Export("project-report.csv");
   }  
}`

Would this be enough?

**Comment by unitystevem** [comment]
I think so. That just needs testing to verify that it works (if you haven't already), and the sample code put into in the documentation, and then I think we can close this issue.

**Comment by mtrive** [comment]
We have unit tests the use that code but it's not tested in a CI environment.

**Comment by mtrive** [comment]
Added a section in the docs on how to run from command line in b33c52317a7695130b421a3a184af990bd48933a
