### ISSUE TITLE
Don't work on Unity 2018.4.6f1

### ISSUE THREAD

**Issue by Temka193** [mtrive/ProjectAuditor#88]
On open "Project Auditor" window:

`ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
System.Reflection.Assembly.GetTypes () (at <df7127ba07dc446d9f5831a0ec7b1d63>:0)
Unity.ProjectAuditor.Editor.ScriptAuditor+<GetAnalyzerTypes>d__15.MoveNext () (at Library/PackageCache/com.unity.project-auditor@9fd2146bc61c2e810f04679a2396e3cde76ea111/Editor/Script/ScriptAuditor.cs:204)
Unity.ProjectAuditor.Editor.ScriptAuditor.LoadDatabase (System.String path) (at Library/PackageCache/com.unity.project-auditor@9fd2146bc61c2e810f04679a2396e3cde76ea111/Editor/Script/ScriptAuditor.cs:195)
Unity.ProjectAuditor.Editor.ProjectAuditor.LoadDatabase (System.String path) (at Library/PackageCache/com.unity.project-auditor@9fd2146bc61c2e810f04679a2396e3cde76ea111/Editor/ProjectAuditor.cs:124)
Unity.ProjectAuditor.Editor.ProjectAuditor.LoadDatabase () (at Library/PackageCache/com.unity.project-auditor@9fd2146bc61c2e810f04679a2396e3cde76ea111/Editor/ProjectAuditor.cs:130)
Unity.ProjectAuditor.Editor.ProjectAuditor..ctor () (at Library/PackageCache/com.unity.project-auditor@9fd2146bc61c2e810f04679a2396e3cde76ea111/Editor/ProjectAuditor.cs:95)
Unity.ProjectAuditor.Editor.ProjectAuditorWindow.OnEnable () (at Library/PackageCache/com.unity.project-auditor@9fd2146bc61c2e810f04679a2396e3cde76ea111/Editor/UI/ProjectAuditorWindow.cs:102)
UnityEditor.EditorWindow:GetWindow(Type)
Unity.ProjectAuditor.Editor.ProjectAuditorWindow:ShowWindow() (at Library/PackageCache/com.unity.project-auditor@9fd2146bc61c2e810f04679a2396e3cde76ea111/Editor/UI/ProjectAuditorWindow.cs:580)
`

On click "Analyze":
`NullReferenceException: Object reference not set to an instance of an object
Unity.ProjectAuditor.Editor.ProjectAuditorWindow.Analyze () (at Library/PackageCache/com.unity.project-auditor@9fd2146bc61c2e810f04679a2396e3cde76ea111/Editor/UI/ProjectAuditorWindow.cs:180)
Unity.ProjectAuditor.Editor.ProjectAuditorWindow.DrawToolbar () (at Library/PackageCache/com.unity.project-auditor@9fd2146bc61c2e810f04679a2396e3cde76ea111/Editor/UI/ProjectAuditorWindow.cs:545)
Unity.ProjectAuditor.Editor.ProjectAuditorWindow.OnGUI () (at Library/PackageCache/com.unity.project-auditor@9fd2146bc61c2e810f04679a2396e3cde76ea111/Editor/UI/ProjectAuditorWindow.cs:122)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <df7127ba07dc446d9f5831a0ec7b1d63>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <df7127ba07dc446d9f5831a0ec7b1d63>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <df7127ba07dc446d9f5831a0ec7b1d63>:0)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:342)
UnityEditor.HostView.Invoke (System.String methodName) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:336)
UnityEditor.HostView.InvokeOnGUI (UnityEngine.Rect onGUIPosition, UnityEngine.Rect viewRect) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:310)
UnityEditor.DockArea.DrawView (UnityEngine.Rect viewRect, UnityEngine.Rect dockAreaRect, System.Boolean customBorder, System.Boolean floatingWindow, System.Boolean isBottomTab) (at C:/buildslave/unity/build/Editor/Mono/GUI/DockArea.cs:361)
UnityEditor.DockArea.OldOnGUI () (at C:/buildslave/unity/build/Editor/Mono/GUI/DockArea.cs:320)
UnityEngine.Experimental.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 worldTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout) (at C:/buildslave/unity/build/Modules/UIElements/IMGUIContainer.cs:266)
UnityEngine.Experimental.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, UnityEngine.Matrix4x4 worldTransform, UnityEngine.Rect clippingRect) (at C:/buildslave/unity/build/Modules/UIElements/IMGUIContainer.cs:438)
UnityEngine.Experimental.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e) (at C:/buildslave/unity/build/Modules/UIElements/IMGUIContainer.cs:421)
UnityEngine.Experimental.UIElements.IMGUIContainer.HandleEvent (UnityEngine.Experimental.UIElements.EventBase evt) (at C:/buildslave/unity/build/Modules/UIElements/IMGUIContainer.cs:401)
UnityEngine.Experimental.UIElements.EventDispatcher.ProcessEvent (UnityEngine.Experimental.UIElements.EventBase evt, UnityEngine.Experimental.UIElements.IPanel panel) (at C:/buildslave/unity/build/Modules/UIElements/EventDispatcher.cs:511)
UnityEngine.Experimental.UIElements.EventDispatcher.Dispatch (UnityEngine.Experimental.UIElements.EventBase evt, UnityEngine.Experimental.UIElements.IPanel panel, UnityEngine.Experimental.UIElements.DispatchMode dispatchMode) (at C:/buildslave/unity/build/Modules/UIElements/EventDispatcher.cs:307)
UnityEngine.Experimental.UIElements.BaseVisualElementPanel.SendEvent (UnityEngine.Experimental.UIElements.EventBase e, UnityEngine.Experimental.UIElements.DispatchMode dispatchMode) (at C:/buildslave/unity/build/Modules/UIElements/Panel.cs:176)
UnityEngine.Experimental.UIElements.UIElementsUtility.DoDispatch (UnityEngine.Experimental.UIElements.BaseVisualElementPanel panel) (at C:/buildslave/unity/build/Modules/UIElements/UIElementsUtility.cs:245)
UnityEngine.Experimental.UIElements.UIElementsUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at C:/buildslave/unity/build/Modules/UIElements/UIElementsUtility.cs:68)
UnityEngine.GUIUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at C:/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:179)
`

**Comment by mtrive** [comment]
Thanks for reporting this. Any chance you could try to repro using the latest 2018 LTS?

**Comment by DmitriyYukhanov** [comment]
Just to let you know, it works fine for me at 2018.4.12.

**Comment by mtrive** [comment]
It works for me too, so it's either an edge case specific to the project or to the Unity version.

**Comment by Temka193** [comment]
I'll see what could be the problem, as soon as there is time

**Comment by Temka193** [comment]
surprisingly, but I installed again and it worked

**Comment by mtrive** [comment]
glad it works again

**Comment by Temka193** [comment]
Open please

**Comment by Temka193** [comment]
It don't work again

**Comment by Temka193** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/11135702/73064752-fa243880-3eb2-11ea-9b2a-2cefe22c943f.png)
Assembly Editor don't load
