### ISSUE TITLE
Precompiled assemblies analysis

### ISSUE THREAD

**Issue by mtrive** [mtrive/ProjectAuditor#97]
At the moment, only assemblies compiled from source code in the Editor are analyzed. It would be good to be able to also analyze pre-compiled ones.

**Comment by soraryu** [comment]
That's actually incorrect. Only assemblies from Assets folder seem to be analyzed. Assemblies from packages (which are not precompiled assemblies) are also not analzyed.

**Comment by mtrive** [comment]
> That's actually incorrect. Only assemblies from Assets folder seem to be analyzed. Assemblies from packages (which are not precompiled assemblies) are also not analzyed.

You are right. In this recent PR: https://github.com/mtrive/ProjectAuditor/pull/102 we discussed whether we should analyze package assemblies or not. Later this week we will push a change that will allow you to analyze package assemblies as well.

**Comment by soraryu** [comment]
Looking forward to that! I tried the Auditor on my "package master" project and was surprised to get 0 assemblies :)

**Comment by mtrive** [comment]
@soraryu Are you still experiencing any problem?

**Comment by soraryu** [comment]
I'll test again this week and update here. Looking forward to the partially async analysis stuff!
